### ISSUE TITLE
Add $contrast as third parameter of contrast-color() function.

### ISSUE THREAD

**Issue by imkremen** [xi/sass-planifolia#3]
Add $contrast as third parameter of contrast-color() function.
If both colors meet the contrast requirements, $color1 will be used.

Example:
```
  $color: #6170c2;
  background-color: $color;
  color: contrast-color($color, white, black, 4.5); 
  // contrast($color, white) => 4.56;
  // contrast($color, black) => 4.6
```

Result CSS:
```
  background-color: #6170c2;
  color: white; 
```

**Comment by xi** [comment]
See https://github.com/xi/sass-planifolia/pull/4#issuecomment-379523661
